tolking/element-pro-components

- src/Breadcrumb/Breadcrumb.vue
- src/Checkbox/Checkbox.vue
- src/CheckboxButton/CheckboxButton.vue
- src/Form/FormItem.vue
- src/Menu/Menu.vue
- src/Radio/Radio.vue
- src/RadioButton/RadioButton.vue
- src/Select/Select.vue
- src/Table/Table.vue
- src/composables/form.ts
- src/composables/public.ts
- src/composables/table.ts
- src/mixins/index.ts
- src/mixins/select.ts
- src/utils/filter.ts
- src/utils/router.ts
- fix filterRouterByHidden without check the deep children
> refactor: optimized code and fix bug

- example/src/layout/Layout.vue
- src/Layout/Layout.vue
- src/Layout/LayoutAside.vue
- src/Layout/LayoutHeader.vue
- src/Layout/LayoutMain.vue
- src/Layout/index.ts
- src/Table/Table.vue
- src/composables/public.ts
- src/styles/index.css
- vetur/attributes.json
- vetur/tags.json
- Layout: add prop for Menu
- Layout: add transition
- fix Table error when no total
> refactor(Layout): optimized style

- src/Form/Form.vue
- src/Form/FormItem.vue
- src/composables/form.ts
- src/types/index.ts
- expose form methods
- optimize the display on phone
> feat(Form): expose form methods

- docs/docs/zh-CN/components/Crud.md
- docs/docs/zh-CN/components/Table.md
- docs/src/components/NavHeader.vue
- docs/src/main.ts
- src/Crud/Crud.vue
- src/composables/crud.ts
- miss form menu
- miss search menu when menu is false
- error when menu is true
> fix(Crud):  menu error

- src/Crud/Crud.vue
- src/Form/Form.vue
- src/utils/filter.ts
- fix(Form): disabled reset button when click submit
- fix(Crud): miss ElButton
> fix(Form): disabled reset button when click submit

- docs/src/views/Crud.vue
- docs/src/views/Table.vue
- src/ColumnSetting/ColumnSetting.vue
- src/ColumnSetting/index.ts
- src/Crud/Crud.vue
- src/Form/Form.vue
- src/Form/FormItem.vue
- src/Table/Table.vue
- src/composables/crud.ts
- src/composables/form.ts
- src/composables/table.ts
- src/index.ts
- src/types/breadcrumb.ts
- src/types/checkbox.ts
- src/types/columnSetting.ts
- src/types/crud.ts
- src/types/index.ts
- src/types/inputTag.ts
- src/types/layout.ts
- src/types/menu.ts
- src/types/radio.ts
- src/types/select.ts
- src/types/table.ts
- test/table.spec.ts
- ColumnSetting: add ProColumnSetting
- Crud: add action slot
- Table: add hide for columns
>  feat(ColumnSetting): add ProColumnSetting

- src/Table/TableComponent.ts
This reverts commit efd0b4df30609f3b98c2db373cbafa7cc5518a0c.
> Revert "feat(Table): optimization"

- src/Select/Select.vue
- src/styles/breadcrumb.css
- src/styles/checkbox-button.css
- src/styles/checkbox.css
- src/styles/column-setting.css
- src/styles/form.css
- src/styles/menu.css
- src/styles/radio-button.css
- src/styles/radio.css
- src/styles/tabs.css
- fix(Select): the label display error
- fix(styles): Missing css style
- fix(Form): styles error
> fix(Select): the label display error

- CHANGELOG.md
- docs/src/views/Form.vue
- package.json
- src/Crud/Crud.vue
- src/TreeSelect/TreeSelect.vue
- src/composables/crud.ts
- src/composables/form.ts
- src/composables/inputTag.ts
- src/composables/public.ts
- src/composables/select.ts
- src/composables/table.ts
- src/composables/tabs.ts
- src/types/crud.ts
- src/types/form.ts
- src/types/public.ts
- src/types/table.ts
- fix(TreeSelect): error when without model-value
- type: optimization types
close #77
> chore: updata Changelog

- src/composables/form.ts
- src/composables/table.ts
- src/types/crud.ts
- src/types/form.ts
- src/types/table.ts
- tsconfig.json
> fix(types): type error when building

- src/Form/Form.ts
- src/Form/FormComponent.ts
- src/Table/props.ts
- src/TreeSelect/TreeSelect.vue
- src/composables/select.ts
- src/element-pro-components.ts
- src/styles/menu.css
- test/composables.spec.ts
- optimization type
- fix(test): useRow error
- fix(Menu): horizontal style error
> optimization type

- src/AutocompleteTag/AutocompleteTag.ts
- src/AutocompleteTag/props.ts
- src/InputTag/InputTag.ts
- src/InputTag/props.ts
- src/composables/inputTag.ts
- src/styles/autocomplete-tag.css
- src/styles/input-tag.css
- refactor(InputTag|AutocompleteTag): better reuse of code
- feat(InputTag|AutocompleteTag): sync the style change
> refactor(InputTag|AutocompleteTag): better reuse of code

- demo/Layout/keep-alive.vue
- demo/Layout/slots.vue
- demo/Layout/transition.vue
- docs/docs/en-US/components/Layout.md
- docs/docs/zh-CN/components/Layout.md
- docs/src/styles/markdown.css
- src/Layout/Layout.ts
- src/Layout/props.ts
- src/styles/layout.css
- src/styles/vars.css
- src/types/router.ts
- test/layout.spec.ts
- refactor(Layout): reimplement the KeepAlive
- refactor(Layout): remove the props fixed-main
- refactor(Layout): remove the slots main-top and main-botton
- refactor(Layout): remove styles about main and fixed-main
> refactor(Layout): reimplement the KeepAlive

- demo/Descriptions/slots.vue
- docs/docs/en-US/components/Descriptions.md
- docs/docs/zh-CN/components/Descriptions.md
- src/Descriptions/Descriptions.ts
- src/Descriptions/type.ts
- refacto(Descriptions): rename the slot parameter to item
- refacto(Descriptions): change the renderLabel parameter to column
> refacto(Descriptions): rename the slot parameter to item

- build/plugin/demo.ts
- demo/Layout/base.vue
- demo/Layout/routes.vue
- demo/Menu/base.vue
- demo/Menu/routes.vue
- demo/Tabs/ref.vue
- docs/src/components/AlgoliaSearch.vue
- docs/src/components/ProCode.vue
- docs/src/composables/index.ts
- docs/src/composables/stackBlitz.ts
- docs/src/lang/index.ts
- docs/src/main.ts
- docs/src/styles/docs.css
- docs/src/styles/index.css
- docs/src/utils/index.ts
- package.json
- Edit on StackBlitz
- View on Github
- Copy code
> feat(docs): extended demo capabilities

- CHANGELOG.md
- package.json
feat
- Form: prevent default submit (#308)
- type: more elegant type deduction for prop in Columns (#307)
refacto
- Layout: optimize the collapse of the menu (#309)
- composables: move the composables function (#310)
- props: export all props (#312)
- emits: export all emits (#313)
> chore: update Changelog

- src/AutocompleteTag/index.test.ts
- src/InputTag/InputTag.ts
- src/InputTag/index.test.ts
- src/InputTag/useInputTag.ts
- src/styles/input-tag.css
Support to remove the Tag content by the `Backspace` keys.
> feat(InputTag):  A11y  enhancements

- demo/Form/slots.vue
- docs/docs/en-US/components/Form.md
- docs/docs/zh-CN/components/Form.md
- docs/src/components/ProCode.vue
- src/Form/FormItem.ts
- src/Form/index.test.ts
[prop]           -> form-[prop]
[prop]-label -> form-[prop]-label
[prop]-error -> form-[prop]-error
> refacto(Form): modify the name of the slot

- demo/Tabs/before-add.vue
- demo/Tabs/before-leave.vue
- demo/Tabs/keep-hidden-route.vue
- docs/docs/en-US/components/Tabs.md
- docs/docs/zh-CN/components/Tabs.md
- docs/src/views/Form.vue
- docs/src/views/Table.vue
- src/Tabs/Tabs.ts
- src/Tabs/props.ts
- src/Tabs/type.ts
- src/Tabs/useTabs.ts
- [feat(Tabs): add beforeAdd attribute](https://github.com/tolking/element-pro-components/commit/3ddb02533b21c4962739598ffcc430cef34c1d19)
- [fix(Tabs): the before-leave not work](https://github.com/tolking/element-pro-components/commit/c3f891e764f65cdac8ff2671652b21d881c8d613)
> feat(Tabs): add beforeAdd attribute

- CHANGELOG.md
- package.json
feat
- Tabs: add keepHiddenRoute attribute (#360)
- Tabs: add beforeAdd attribute (#361)
- Tabs: optimized style
close #359
> Releases 1.2.1

- src/Menu/Menu.ts
Reverts tolking/element-pro-components#365
> Revert "fix(Menu): path error when there is only one route in children"

- CHANGELOG.md
- package.json
feat
- Tabs: record the route name (#369)
- InputTag: optimization tag styles (#378)
- Menu: optimize performance of hasMultiChild function (#368)
fix
- Menu: path error when only one route in children (#367)
- TreeSelect: lint error (#377)
other
- add attribute enum autosuggestion for web-types (#373)
- docs: split AutocompleteTag component (#381)
> Releases 1.2.2

- build/plugin/demo.ts
- vite.config.ts
nodejs^14 is not supported replaceAll, pnpm dev , str.replaceAll is not a function
> fix(demo): nodejs 14 is not supported replaceAll

- demo/Form/array.vue
- docs/docs/en-US/components/Form.md
- docs/docs/zh-CN/components/Form.md
- src/Form/ArrayForm.ts
- src/Form/Form.ts
- src/Form/FormItem.ts
- src/Form/FormList.ts
- src/Form/index.test.ts
- src/Form/index.ts
- src/Form/props.ts
- src/Form/type.ts
- src/Form/useForm.ts
- src/styles/form.css
extract ArrayForm component from FormItem
> refactor(Form): add type and max attributes

- CHANGELOG.md
- package.json
feat
- FilterRoutes: Ignore hidden routes (#396)
- Form: add array attribute for using Array Form (#402) (#404) (#406)
- Form: add inject attributes (#403)
- Form: support the generation of GroupForm through config (#405)
fix
- FilterRoutes: optimization styles (#397)
- Tabs: name attribute is not added when using beforeAdd (#407)
> Releases 1.2.4

- CHANGELOG.md
- package.json
feat
- Menu: support defining the group of menu (#409)
- Checkbox|Radio|Select: support nested value for config (#410)
- Form: generation the TabsForm based on columns (#413)
- Form: generation the CollapseForm based on columns (#414)
- Form: generation the StepsForm based on columns (#415)
- Form: optimize code (#416)
- Form: support bind attributes to group forms (#417)
- Crud: sync the group form changes (#418)
other
- build: change join to resolve (#412)
- docs: optimize SSG about teleports (#419)
- docs: optimize document directory (#420)
> Releases 1.2.5

- CHANGELOG.md
- package.json
fix
- build: missing the code prompt file (#422)
> Releases 1.2.6

- docs/en-US/guide/index.md
- docs/zh-CN/guide/index.md
> docs: updata

- CHANGELOG.md
- package.json
feat
- Form: solving the attrs (#424)
fix
- Form: the style link error (#426)
- optimize SSG about teleports (#428)
> Releases 1.2.7

- docs/en-US/guide/contributing.md
- docs/en-US/guide/introduction.md
- docs/src/router/en-US.ts
- docs/src/router/zh-CN.ts
- docs/zh-CN/guide/contributing.md
- docs/zh-CN/guide/introduction.md
> docs: add Contributing.md

- src/Form/props.ts
> type(Form): optimization type

- src/Form/ArrayForm.ts
- src/utils/util.ts
> fix(Form): validation error of ArrayForm

- src/Form/Form.ts
> fix(Form): disable reset button when submit

- README.md
- docs/en-US/guide/contributing.md
- docs/zh-CN/guide/contributing.md
> docs: update contributing

- CHANGELOG.md
- README.md
- package.json
fix
- build Error Nodejs^15 Cannot find module 'node:path' (#431)
- Form: validation error of ArrayForm (#440)
- Form: disable reset button when submit (#442)
other
- add CODE_OF_CONDUCT.md (#432)
- add issue template (#433)
- docs: add contributing.md (#436)
- add pull_request_template.md (#437)
- Form: optimization type (#438)
- update README (#439)
> chore: Releases 1.2.8

- src/Form/FormComponent.ts
- src/Form/FormItem.ts
- src/Form/props.ts
> refactor(Form): FormComponent

- docs/en-US/guide/index.md
- docs/zh-CN/guide/index.md
- src/utils/helper.ts
- src/utils/index.ts
> feat: add ElementProResolver from unplugin-vue-components

- build/prerender.ts
- docs/src/entry-server.ts
> docs: fix teleports error caused by formatting code

- CHANGELOG.md
- package.json
> chore: releases v1.2.9

- build/prerender.ts
- docs/src/composables/stackBlitz.ts
- docs/src/entry-server.ts
- package.json
> chore: optimize dependencies

- src/Crud/Crud.ts
- src/Crud/index.test.ts
> fix(Crud): the size of button is overwritten

- CHANGELOG.md
- package.json
> chore: releases v1.2.10

- src/Descriptions/Descriptions.ts
- src/Descriptions/index.test.ts
> fix(Descriptions): avoid render header when without slot

- src/styles/card.css
- src/styles/crud.css
- src/styles/filter-routes.css
- src/styles/table.css
> chore: optimize CSS variables

- demo/Layout/slots.vue
- docs/en-US/components/Layout.md
- docs/src/main.ts
- docs/zh-CN/components/Layout.md
- src/Layout/Layout.ts
- src/Layout/index.test.ts
> feat(Layout): add collapse-button slot

- demo/Form/modelKey.vue
- docs/en-US/components/Form.md
- docs/zh-CN/components/Form.md
- src/Form/FormComponent.ts
- src/Form/FormItem.ts
- src/Form/index.test.ts
- src/Form/props.ts
- src/Form/type.ts
> feat(Form): support custom v-model arguments

- CHANGELOG.md
- package.json
> chore: releases v1.2.11

- demo/Crud/slots-dialog.vue
- demo/Crud/slots-form.vue
- demo/Crud/slots-table.vue
- docs/en-US/components/Crud.md
- docs/src/main.ts
- docs/zh-CN/components/Crud.md
- src/Crud/Crud.ts
- src/Crud/index.test.ts
`crud-table` `crud-dialog` `crud-search` `crud-form` `crud-detail`
> feat(Crud): add some slots

- demo/Crud/dialog-open.vue
- docs/en-US/components/Crud.md
- docs/zh-CN/components/Crud.md
- src/Crud/Crud.ts
- src/Crud/index.test.ts
- src/Crud/type.ts
- src/Crud/useCrud.ts
> feat(Crud): add expose function openDialog and closeDialog

- CHANGELOG.md
- docs/src/router/en-US.ts
- docs/src/router/zh-CN.ts
> chore: releases v1.2.12

- src/Select/Select.ts
- src/TreeSelect/TreeSelect.ts
> refactor(Select): remove the slot parameter data

- src/Table/TableItem.ts
> refactor(Table): remove the deprecated slots

- demo/Form/label-position.vue
- src/Form/FormItem.ts
- src/Form/useForm.ts
> refactor(Form): remove the deprecated slots

- src/Checkbox/Checkbox.ts
> feat(Checkbox): sync label prop to value

- src/Crud/useCrud.ts
> refactor(Crud): remove the deprecated slots

- src/Descriptions/Descriptions.ts
> refactor(Descriptions): remove the deprecated slots

- src/composables/breakpoint.ts
- src/utils/index.test.ts
- src/utils/util.ts
> refactor: remove the deprecated function

- docs/zh-CN/components/Layout.md
> docs: typo

- CHANGELOG.md
- package.json
> chore: releases v1.3.0

- src/AutocompleteTag/AutocompleteTag.ts
- src/Checkbox/Checkbox.ts
- src/Checkbox/props.ts
- src/ColumnSetting/ColumnSetting.ts
- src/ColumnSetting/props.ts
- src/Crud/Crud.ts
- src/Descriptions/Descriptions.ts
- src/FilterRoutes/FilterRoutes.ts
- src/FilterRoutes/props.ts
- src/Form/Form.ts
- src/InputTag/InputTag.ts
- src/InputTag/props.ts
- src/InputTag/useInputTag.ts
- src/Layout/Layout.ts
- src/Layout/props.ts
- src/Radio/Radio.ts
- src/Radio/props.ts
- src/Select/Select.ts
- src/Select/props.ts
- src/Table/Table.ts
- src/Table/props.ts
- src/TreeSelect/TreeSelect.ts
- src/TreeSelect/props.ts
- src/composables/index.test.ts
- src/composables/public.ts
> refactor: use useSplitReactive to replace reactiveOmit and reactivePick

- src/Table/props.ts
> fix: warn error about prevIcon and nextIcon

- CHANGELOG.md
- package.json
> chore: releases v1.3.1

- .github/workflows/deploy.yml
- .github/workflows/release.yml
- .github/workflows/test-build.yml
- .github/workflows/test.yml
> ci: updata dependencies of workflows

- src/Form/Form.ts
- src/Serach/Search.ts
- src/Serach/useSearch.ts
> fix(Search): display error when there is too much content in the menu slot

- src/Crud/useCrud.ts
- src/Form/useForm.ts
- src/Serach/useSearch.ts
> fix: error when switching to multiple languages

- .gitignore
- .vscode/launch.json
- vite.config.ts
> chore: add breakpoint debugging config for VS Code

- src/styles/crud.css
> fix(Crud): the menu styles

- demo/Tabs/contextmenu.vue
- docs/en-US/components/Tabs.md
- docs/en-US/guide/i18n.md
- docs/src/lang/index.ts
- docs/src/layout/Layout.vue
- docs/src/layout/Refresh.vue
- docs/src/router/index.ts
- docs/zh-CN/components/Tabs.md
- docs/zh-CN/guide/i18n.md
- src/Tabs/Tabs.ts
- src/Tabs/index.test.ts
- src/Tabs/props.ts
- src/Tabs/type.ts
- src/Tabs/useTabs.ts
- src/styles/tabs.css
> feat(Tabs): add contextmenu prop

- docs/en-US/guide/index.md
- docs/zh-CN/guide/index.md
- package.json
- pnpm-lock.yaml
> chore: move vue-router to peerDependencies

- build/build-locale.ts
- build/sync-types.ts
- demo/I18n/base.vue
- docs/en-US/guide/i18n.md
- docs/src/components/ProCode.vue
- docs/src/components/PwaPopup.vue
- docs/src/lang/index.ts
- docs/src/tsconfig.json
- docs/zh-CN/guide/i18n.md
- package.json
- src/Crud/index.test.ts
- src/Crud/useCrud.ts
- src/Form/useForm.ts
- src/Search/useSearch.ts
- src/Tabs/useTabs.ts
- src/composables/index.ts
- src/composables/locale.ts
- src/locale/en.ts
- src/locale/zh-cn.ts
- vite.config.ts
> feat: add multi-language files

- package.json
> chore: add exports for locale and styles

- src/Breadcrumb/Breadcrumb.ts
- src/Checkbox/Checkbox.ts
- src/Descriptions/Descriptions.ts
- src/Form/ArrayForm.ts
- src/Form/CollapseForm.ts
- src/Form/FormList.ts
- src/Form/GroupForm.ts
- src/Form/StepsForm.ts
- src/Form/TabsForm.ts
- src/InputTag/InputTag.ts
- src/Menu/Menu.ts
- src/Radio/Radio.ts
- src/Select/Select.ts
- src/Table/Table.ts
- src/Table/TableItem.ts
- src/TreeSelect/TreeSelect.ts
> pref: add key fro list VNode

- package.json
> chore: optimize the exports

- demo/Tabs/slots.vue
- docs/en-US/components/Tabs.md
- docs/zh-CN/components/Tabs.md
- src/Tabs/Tabs.ts
- src/Tabs/index.test.ts
- src/Tabs/type.ts
- src/Tabs/useTabs.ts
breaking changes
the `label` slot parameter has been changed to `RouteLocationNormalizedLoadedGeneric`
> feat(Tabs): add query and hash when jumping

- src/Tabs/Tabs.ts
- src/Tabs/type.ts
- src/Tabs/useTabs.ts
> type(Tabs): use RouteLocationNormalizedLoaded replace RouteLocationNormalizedLoadedGeneric

- docs/en-US/components/Tabs.md
- docs/src/components/NavHeader.vue
- docs/src/layout/Layout.vue
- docs/zh-CN/components/Tabs.md
> docs: optimize multi-language switching logic

- CHANGELOG.md
- package.json
> chore: releases v1.4.0

- demo/Form/ref.vue
- docs/en-US/components/Form.md
- docs/zh-CN/components/Form.md
- src/Form/FormComponent.ts
- src/Form/index.test.ts
- src/Form/type.ts
- src/types/props.ts
> feat(Form): support binding component instances through ref

- src/Form/FormComponent.ts
> pref(Form): optimize ProFormComponent

- src/Form/ArrayForm.ts
- src/locale/en.ts
- src/locale/zh-cn.ts
> chore(Form): add aria-label for ArrayForm

- src/Crud/Crud.ts
- src/Table/Table.ts
- src/Table/useTable.ts
> fix(Table): the load triggered multiple times when page-size is changed

- src/Form/FormComponent.ts
- src/Form/FormItem.ts
- src/Form/index.test.ts
- src/Form/props.ts
fix
> [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.
> fix(Form): optimize ref bind for ProFormComponent

- src/Table/Table.ts
- src/Table/index.test.ts
> fix(Table): pagination are not displayed when using pageCount

- docs/src/components/NavHeader.vue
- docs/src/lang/index.ts
> docs: add theme switching animation

- CHANGELOG.md
- package.json
> chore: releases v1.4.1

- src/Form/type.ts
> type(Form): autocomplete names from global components

- src/composables/locale.ts
> type: [useLocale] autocomplete locale field keys
